backend:
  name: github
  repo: scinio/deaxsadventure
  branch: main
  auth_type: token

media_folder: "assets/comics"
public_folder: "/assets/comics"

collections:
  - name: "config"
    label: "Site Configuration"
    files:
      - label: "Comic List"
        name: "comic-list"
        file: "assets/data.json"
        fields:
          - label: "Pages"
            name: "pages"
            widget: "list"
            fields:
              - { label: "Image", name: "image", widget: "image" }